Repository kanisterio/kanister, pull requests merged in 2022-04, with the labels that each got.

#1356 Update ubi-minimal base image to latest
  Dockerfile.in
  docker/controller/Dockerfile
  docker/tools/Dockerfile
Labels: kueue

#1347 Add BUILD.md Development Guide
  BUILD.md
  Makefile
  build/check.sh
  graphic/kanister_workflow.png
Labels: documentation, kueue

#1359 Kanister docs update to version 0.76.0
  examples/aws-rds/postgresql/README.md
  examples/aws-rds/postgresql/rds-postgres-blueprint.yaml
  examples/aws-rds/postgresql/rds-postgres-dump-blueprint.yaml
  examples/cassandra/README.md
  examples/cassandra/cassandra-blueprint.yaml
  examples/couchbase/blueprint-v2/couchbase-blueprint.yaml
  examples/couchbase/couchbase-blueprint.yaml
  examples/csi-snapshot/README.md
  examples/elasticsearch/README.md
  examples/elasticsearch/blueprint-v2/elasticsearch-blueprint.yaml
  examples/elasticsearch/elasticsearch-blueprint.yaml
  examples/etcd/etcd-in-cluster/k8s/etcd-incluster-blueprint.yaml
  examples/etcd/etcd-in-cluster/ocp/etcd-incluster-ocp-blueprint.yaml
  examples/foundationdb/README.md
  examples/foundationdb/blueprint-v2/foundationdb-blueprint.yaml
  examples/kafka/adobe-s3-connector/README.md
  examples/maria/blueprint-v2/maria-blueprint.yaml
  examples/maria/maria-blueprint.yaml
  examples/mongodb-deploymentconfig/README.md
  examples/mongodb-deploymentconfig/blueprint-v2/mongo-dep-config-blueprint.yaml
  examples/mongodb-deploymentconfig/mongo-dep-config-blueprint.yaml
  examples/mongodb-restic/README.md
  examples/mongodb-restic/mongodb-blueprint.yaml
  examples/mongodb/README.md
  examples/mongodb/blueprint-v2/mongo-blueprint.yaml
  examples/mongodb/mongo-blueprint.yaml
  examples/mssql/README.md
  examples/mssql/blueprint-v2/mssql-blueprint.yaml
  examples/mssql/mssql-blueprint.yaml
  examples/mysql-deploymentconfig/README.md
  examples/mysql-deploymentconfig/blueprint-v2/mysql-dep-config-blueprint.yaml
  examples/mysql-deploymentconfig/mysql-dep-config-blueprint.yaml
  examples/mysql/README.md
  examples/mysql/blueprint-v2/mysql-blueprint.yaml
  examples/mysql/mysql-blueprint.yaml
  examples/postgresql-deploymentconfig/README.md
  examples/postgresql-deploymentconfig/blueprint-v2/postgres-dep-config-blueprint.yaml
  examples/postgresql-deploymentconfig/postgres-dep-config-blueprint.yaml
  examples/postgresql-ha/hook-blueprint/README.md
  examples/postgresql-wale/README.md
  examples/postgresql-wale/postgresql-blueprint.yaml
  examples/postgresql/README.md
  examples/postgresql/blueprint-v2/postgres-blueprint.yaml
  examples/postgresql/postgres-blueprint.yaml
  examples/postgresql/v10.16.2/postgres-blueprint.yaml
  examples/time-log/blueprint.yaml
  examples/time-log/time-logger-deployment.yaml
  helm/kanister-operator/Chart.yaml
  helm/kanister-operator/values.yaml
  helm/profile/Chart.yaml
  pkg/app/csi-snapshot.go
  pkg/function/data_test.go
  pkg/function/export_rds_snapshot_location.go
  pkg/function/kube_exec_test.go
  pkg/function/kube_task_test.go
  pkg/function/utils.go
  pkg/kube/pod_test.go
  pkg/param/param_test.go
  pkg/testing/e2e_test.go
  scripts/get.sh
Labels: kueue

#1297 Support an eventual phase for the blueprint actions
  docs/architecture.rst
  docs/templates.rst
  docs/tutorial.rst
  pkg/apis/cr/v1alpha1/types.go
  pkg/apis/cr/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/customresource/actionset.yaml
  pkg/customresource/blueprint.yaml
  pkg/param/param.go
  pkg/param/param_test.go
  pkg/phase.go
  pkg/phase_test.go
Labels: kueue

#1337 Add test for `deferPhase` in blueprint actions
  .travis.yml
  pkg/controller/controller_test.go
  pkg/testutil/testutil.go
  pkg/testutil/testutil_test.go
Labels: kueue

#1375 Fix GitHub Image Push Permissions
  .github/workflows/main.yaml
  README.md
Labels: kueue

#1370 Add blueprint validation logic to deferPhases as well
  pkg/blueprint/validate/validate.go
  pkg/blueprint/validate/validate_test.go
Labels: kueue

#1382 Enable grpc for connecting to Kopia API Server
  pkg/kopia/connect.go
Labels: kueue

#1350 add optional wait flag to scaleWorkload function
  docs/functions.rst
  pkg/function/scale_test.go
  pkg/function/scale_workload.go
  pkg/kube/workload.go
  pkg/kube/workload_test.go
Labels: kueue

#1390 Strictly match Group in ResourceTypeMatcher: K8s core group
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: kueue

#1391 Fix flaky Defer Phase tests
  pkg/consts/consts.go
  pkg/controller/controller_test.go
  pkg/function/kube_task_test.go
  pkg/kube/pod_test.go
  pkg/testutil/testutil.go
Labels: kueue

#1393 Don't render artifacts if any of the phases are failed
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: kueue

#1392 Add dependency review GH action
  .github/workflows/dependendy-review.yml
Labels: kueue, dependencies, security

#1394 Compatible ResourceTypeMatcher with exact match for core
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: kueue

#1396 Kanister docs update to version 0.77.0
  examples/aws-rds/postgresql/README.md
  examples/aws-rds/postgresql/rds-postgres-blueprint.yaml
  examples/aws-rds/postgresql/rds-postgres-dump-blueprint.yaml
  examples/cassandra/README.md
  examples/cassandra/cassandra-blueprint.yaml
  examples/couchbase/blueprint-v2/couchbase-blueprint.yaml
  examples/couchbase/couchbase-blueprint.yaml
  examples/csi-snapshot/README.md
  examples/elasticsearch/README.md
  examples/elasticsearch/blueprint-v2/elasticsearch-blueprint.yaml
  examples/elasticsearch/elasticsearch-blueprint.yaml
  examples/etcd/etcd-in-cluster/k8s/etcd-incluster-blueprint.yaml
  examples/etcd/etcd-in-cluster/ocp/etcd-incluster-ocp-blueprint.yaml
  examples/foundationdb/README.md
  examples/foundationdb/blueprint-v2/foundationdb-blueprint.yaml
  examples/kafka/adobe-s3-connector/README.md
  examples/maria/blueprint-v2/maria-blueprint.yaml
  examples/maria/maria-blueprint.yaml
  examples/mongodb-deploymentconfig/README.md
  examples/mongodb-deploymentconfig/blueprint-v2/mongo-dep-config-blueprint.yaml
  examples/mongodb-deploymentconfig/mongo-dep-config-blueprint.yaml
  examples/mongodb-restic/README.md
  examples/mongodb-restic/mongodb-blueprint.yaml
  examples/mongodb/README.md
  examples/mongodb/blueprint-v2/mongo-blueprint.yaml
  examples/mongodb/mongo-blueprint.yaml
  examples/mssql/README.md
  examples/mssql/blueprint-v2/mssql-blueprint.yaml
  examples/mssql/mssql-blueprint.yaml
  examples/mysql-deploymentconfig/README.md
  examples/mysql-deploymentconfig/blueprint-v2/mysql-dep-config-blueprint.yaml
  examples/mysql-deploymentconfig/mysql-dep-config-blueprint.yaml
  examples/mysql/README.md
  examples/mysql/blueprint-v2/mysql-blueprint.yaml
  examples/mysql/mysql-blueprint.yaml
  examples/postgresql-deploymentconfig/README.md
  examples/postgresql-deploymentconfig/blueprint-v2/postgres-dep-config-blueprint.yaml
  examples/postgresql-deploymentconfig/postgres-dep-config-blueprint.yaml
  examples/postgresql-ha/hook-blueprint/README.md
  examples/postgresql-wale/README.md
  examples/postgresql-wale/postgresql-blueprint.yaml
  examples/postgresql/README.md
  examples/postgresql/blueprint-v2/postgres-blueprint.yaml
  examples/postgresql/postgres-blueprint.yaml
  examples/postgresql/v10.16.2/postgres-blueprint.yaml
  examples/time-log/blueprint.yaml
  examples/time-log/time-logger-deployment.yaml
  helm/kanister-operator/Chart.yaml
  helm/kanister-operator/values.yaml
  helm/profile/Chart.yaml
  pkg/app/csi-snapshot.go
  pkg/function/data_test.go
  pkg/function/export_rds_snapshot_location.go
  pkg/function/kube_exec_test.go
  pkg/function/kube_task_test.go
  pkg/function/utils.go
  pkg/kube/pod_test.go
  pkg/testing/e2e_test.go
  scripts/get.sh
Labels: kueue

#1399 Update deferPhaes function to not mention image
  docs/tutorial.rst
Labels: kueue

#1400 Revert "Enable grpc for connecting to Kopia API Server"
  pkg/kopia/connect.go
Labels: kueue

#1403 Kanister docs update to version 0.78.0
  examples/aws-rds/postgresql/README.md
  examples/aws-rds/postgresql/rds-postgres-blueprint.yaml
  examples/aws-rds/postgresql/rds-postgres-dump-blueprint.yaml
  examples/cassandra/README.md
  examples/cassandra/cassandra-blueprint.yaml
  examples/couchbase/blueprint-v2/couchbase-blueprint.yaml
  examples/couchbase/couchbase-blueprint.yaml
  examples/csi-snapshot/README.md
  examples/elasticsearch/README.md
  examples/elasticsearch/blueprint-v2/elasticsearch-blueprint.yaml
  examples/elasticsearch/elasticsearch-blueprint.yaml
  examples/etcd/etcd-in-cluster/k8s/etcd-incluster-blueprint.yaml
  examples/etcd/etcd-in-cluster/ocp/etcd-incluster-ocp-blueprint.yaml
  examples/foundationdb/README.md
  examples/foundationdb/blueprint-v2/foundationdb-blueprint.yaml
  examples/kafka/adobe-s3-connector/README.md
  examples/maria/blueprint-v2/maria-blueprint.yaml
  examples/maria/maria-blueprint.yaml
  examples/mongodb-deploymentconfig/README.md
  examples/mongodb-deploymentconfig/blueprint-v2/mongo-dep-config-blueprint.yaml
  examples/mongodb-deploymentconfig/mongo-dep-config-blueprint.yaml
  examples/mongodb-restic/README.md
  examples/mongodb-restic/mongodb-blueprint.yaml
  examples/mongodb/README.md
  examples/mongodb/blueprint-v2/mongo-blueprint.yaml
  examples/mongodb/mongo-blueprint.yaml
  examples/mssql/README.md
  examples/mssql/blueprint-v2/mssql-blueprint.yaml
  examples/mssql/mssql-blueprint.yaml
  examples/mysql-deploymentconfig/README.md
  examples/mysql-deploymentconfig/blueprint-v2/mysql-dep-config-blueprint.yaml
  examples/mysql-deploymentconfig/mysql-dep-config-blueprint.yaml
  examples/mysql/README.md
  examples/mysql/blueprint-v2/mysql-blueprint.yaml
  examples/mysql/mysql-blueprint.yaml
  examples/postgresql-deploymentconfig/README.md
  examples/postgresql-deploymentconfig/blueprint-v2/postgres-dep-config-blueprint.yaml
  examples/postgresql-deploymentconfig/postgres-dep-config-blueprint.yaml
  examples/postgresql-ha/hook-blueprint/README.md
  examples/postgresql-wale/README.md
  examples/postgresql-wale/postgresql-blueprint.yaml
  examples/postgresql/README.md
  examples/postgresql/blueprint-v2/postgres-blueprint.yaml
  examples/postgresql/postgres-blueprint.yaml
  examples/postgresql/v10.16.2/postgres-blueprint.yaml
  examples/time-log/blueprint.yaml
  examples/time-log/time-logger-deployment.yaml
  helm/kanister-operator/Chart.yaml
  helm/kanister-operator/values.yaml
  helm/profile/Chart.yaml
  pkg/app/csi-snapshot.go
  pkg/function/data_test.go
  pkg/function/export_rds_snapshot_location.go
  pkg/function/kube_exec_test.go
  pkg/function/kube_task_test.go
  pkg/function/utils.go
  pkg/kube/pod_test.go
  pkg/testing/e2e_test.go
  scripts/get.sh
Labels: kueue

#1397 Extend the defer phase state checks in the unit test
  pkg/controller/controller_test.go
Labels: kueue

#1411 Update base image for mongodb image
  build/integration-test.sh
  docker/mongodb/Dockerfile
Labels: kueue

#1415 Enabled mongodb application in kanister CI
  build/integration-test.sh
Labels: kueue

#1419 Update ubi-minimal base image to ubi-minimal:8.5-243
  Dockerfile.in
  docker/controller/Dockerfile
  docker/tools/Dockerfile
Labels: kueue
