Repository kanisterio/kanister, pull requests merged in 2022-10, with the labels that each got.

#1649 Upgrade kopia dependency to custom commit 31017dec554d
  go.mod
  go.sum
Labels: kueue

#1656 Updating CONTRIBUTING.md with slack url
  CONTRIBUTING.md
Labels: kueue, hacktoberfest-accepted

#1650 ActionSet handling perf tweaks
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/testutil/func.go
  pkg/testutil/func_test.go
Labels: kueue

#1664 Add Tags in SnapshotCreate Kopia Wrapper
  pkg/kopia/command/common.go
  pkg/kopia/command/const.go
  pkg/kopia/command/snapshot.go
Labels: kueue

#1668 Follow-up PR for #1650
  pkg/controller/controller.go
Labels: kueue

#1665 Refactor kopia common command wrapper
  pkg/kopia/command/blob.go
  pkg/kopia/command/common.go
  pkg/kopia/command/maintenance.go
  pkg/kopia/command/policy_set_global.go
  pkg/kopia/command/restore.go
  pkg/kopia/command/server.go
  pkg/kopia/command/snapshot.go
  pkg/kopia/maintenance/get_maintenance_owner.go
  pkg/kopia/repository/client.go
Labels: kueue

#1675 Update kanister build to go1.19.2 buster
  docker/build/Dockerfile
Labels: kueue

#1679 Add SnapListByTags Wrapper for Kanister kopia package
  pkg/kopia/command/snapshot.go
Labels: kueue

#1676 Update kanister build v0.0.20
  Makefile
  docker/build/Dockerfile
  go.mod
  go.sum
  pkg/app/kafka.go
  pkg/app/mysql-deploymentconfig.go
  pkg/app/postgresql-deploymentconfig.go
  pkg/app/postgresql.go
  pkg/app/utils.go
  pkg/blockstorage/awsebs/awsebs.go
  pkg/blockstorage/awsebs/awsebs_test.go
  pkg/blockstorage/azure/azure_instance_metadata.go
  pkg/blockstorage/azure/azuredisk.go
  pkg/blockstorage/azure/client.go
  pkg/blockstorage/gcepd/client_test.go
  pkg/blockstorage/ibm/client.go
  pkg/blockstorage/ibm/client_kube_test.go
  pkg/blockstorage/ibm/client_test.go
  pkg/blockstorage/ibm/ibmcloud.go
  pkg/blockstorage/ibm/ibmcloud_test.go
  pkg/blockstorage/vmware/vmware.go
  pkg/blueprint/blueprint.go
  pkg/chronicle/chronicle_pull.go
  pkg/chronicle/chronicle_push.go
  pkg/chronicle/chronicle_push_test.go
  pkg/chronicle/chronicle_test.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/envdir/envdir.go
  pkg/envdir/envdir_test.go
  pkg/eventer/event_recorder.go
  pkg/function/args.go
  pkg/function/delete_data.go
  pkg/function/delete_volume_snapshot.go
  pkg/function/e2e_volume_snapshot_test.go
  pkg/function/export_rds_snapshot_location.go
  pkg/function/restore_rds_snapshot.go
  pkg/kanctl/profile.go
  pkg/kando/chronicle_pull.go
  pkg/kando/output.go
  pkg/kopia/command/parse_command_output.go
  pkg/kopia/snapshot/stream.go
  pkg/kube/exec_test.go
  pkg/kube/log_reader_test.go
  pkg/kube/pod.go
  pkg/kube/podinfo.go
  pkg/kube/podinfo_test.go
  pkg/kube/snapshot/snapshot.go
  pkg/location/location.go
  pkg/log/fluentbit.go
  pkg/log/fluentbit_test.go
  pkg/objectstore/directory.go
  pkg/objectstore/objectstore_test.go
  pkg/openshift/oc.go
  pkg/poll/poll.go
  pkg/restic/restic.go
  pkg/virtualfs/virtualfs.go
Labels: kueue

#1688 Update golang.org/x/text to 0.4.0
  go.mod
  go.sum
Labels: kueue, security

#1687 fix spacing
  pkg/kube/pod.go
  pkg/restic/restic.go
Labels: kueue

#1680 Add Wrapper IsEqualSnapshotCreateStats
  pkg/kopia/command/parse_command_output.go
Labels: kueue

#1689 Remove httpd-tools from kanister-tools image
  docker/tools/Dockerfile
Labels: kueue

#1670 Build other kanister tools with goboring
  .github/workflows/main.yaml
  Makefile
  build/build.sh
Labels: kueue

#1673 Update kopia dockerfile for goboring
  .github/workflows/main.yaml
  Makefile
  build/update_kopia_image.sh
  docker/kopia-build/Dockerfile
  docker/tools/Dockerfile
Labels: kueue

#1662 Add labels to cloned snapshots
  pkg/function/create_csi_snapshot_static.go
  pkg/kube/snapshot/mocks/mock_snapshotter.go
  pkg/kube/snapshot/snapshot.go
  pkg/kube/snapshot/snapshot_alpha.go
  pkg/kube/snapshot/snapshot_beta.go
  pkg/kube/snapshot/snapshot_stable.go
  pkg/kube/snapshot/snapshot_test.go
Labels: kueue

#1697 Add docker to build image
  Makefile
  docker/build/Dockerfile
Labels: kueue

#1702 Update goreleaser to use boring
  .goreleaser.yml
  Makefile
  docker/build/Dockerfile
Labels: kueue

#1705 Use bullseye
  docker/build/Dockerfile
  docker/kanister-elasticsearch/image/Dockerfile
  docker/kanister-elasticsearch/image/esdump-setup.sh
  docker/kopia-build/Dockerfile
  docker/postgres-kanister-tools/Dockerfile
  docker/postgres-tools-9.6/Dockerfile
  pkg/testing/integration_register.go
Labels: kueue

#1698 add labels sanitisation for CreateFromSource
  pkg/kube/snapshot/snapshot_alpha.go
  pkg/kube/snapshot/snapshot_beta.go
Labels: kueue

#1706 Update ubi-minimal base image to ubi-minimal:8.6-985
  Dockerfile.in
  docker/controller/Dockerfile
  docker/tools/Dockerfile
Labels: kueue

#1708 Remove esdump references
  .goreleaser.yml
Labels: bug, kueue

#1709 Downgrade postgres
  docker/postgres-kanister-tools/Dockerfile
  docker/postgres-tools-9.6/Dockerfile
Labels: kueue

#1707 Add back commented tests
  pkg/testing/integration_register.go
Labels: kueue

#1713 Add cleanup for cloned snapshot in test
  pkg/kube/snapshot/snapshot_test.go
Labels: kueue

#1695 Add Name to PodOptions
  pkg/kube/pod.go
  pkg/kube/pod_test.go
Labels: kueue

#1714 Update ubi-minimal base image to ubi-minimal:8.6-994
  Dockerfile.in
  docker/controller/Dockerfile
  docker/tools/Dockerfile
Labels: kueue

#1703 Fips test
  pkg/kube/fips_test.go
Labels: kueue
