Repository kanisterio/kanister, pull requests merged in 2022-06, with the labels that each got.

#1452 revert k8s dependencies to 0.23.5
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
Labels: kueue

#1425 Add K8ssandra Blueprint and example
  examples/k8ssandra/README.md
  examples/k8ssandra/k8ssandra-blueprint.yaml
  examples/k8ssandra/kanister-k8ssandra-rbac.yaml
Labels: kueue

#1404 Add tests for blueprint validate of kanister function with non default versions
  pkg/blueprint/validate/validate_test.go
Labels: kueue

#1460 Improve `IsResAvailableInGroupVersion` to handle non running api servers
  pkg/kube/discover.go
Labels: kueue

#1459 Update README.md for mysql blueprint
  examples/mysql/README.md
Labels: kueue

#1461 RFC: Add design for blueprint and phase progress calculation
  design/progress-tracking.md
  design/update-toc.sh
Labels: kueue, rfc

#1468 Enhance blueprint validator to check for duplicate phase names
  pkg/blueprint/validate/validate.go
  pkg/blueprint/validate/validate_test.go
Labels: kueue

#1479 [Trivial] Update error type in blueprint validator
  pkg/blueprint/validate/validate.go
Labels: kueue

#1483 Update ubi-minimal base image to ubi-minimal:8.6-751.1655117800
  Dockerfile.in
  docker/controller/Dockerfile
  docker/tools/Dockerfile
Labels: kueue, security

#1476 Fix kanister service port issue in case if webhook is disabled
  helm/kanister-operator/templates/_helpers.tpl
  helm/kanister-operator/templates/service.yaml
  pkg/kancontroller/kancontroller.go
Labels: kueue

#1488 Separate Service Secured And Insecured Ports
  helm/kanister-operator/templates/_helpers.tpl
  helm/kanister-operator/values.yaml
Labels: kueue

#1490 Kanister docs update to version 0.80.0
  examples/aws-rds/postgresql/README.md
  examples/aws-rds/postgresql/rds-postgres-blueprint.yaml
  examples/aws-rds/postgresql/rds-postgres-dump-blueprint.yaml
  examples/cassandra/README.md
  examples/cassandra/cassandra-blueprint.yaml
  examples/couchbase/blueprint-v2/couchbase-blueprint.yaml
  examples/couchbase/couchbase-blueprint.yaml
  examples/csi-snapshot/README.md
  examples/elasticsearch/README.md
  examples/elasticsearch/blueprint-v2/elasticsearch-blueprint.yaml
  examples/elasticsearch/elasticsearch-blueprint.yaml
  examples/etcd/etcd-in-cluster/k8s/etcd-incluster-blueprint.yaml
  examples/etcd/etcd-in-cluster/ocp/etcd-incluster-ocp-blueprint.yaml
  examples/foundationdb/README.md
  examples/foundationdb/blueprint-v2/foundationdb-blueprint.yaml
  examples/k8ssandra/README.md
  examples/kafka/adobe-s3-connector/README.md
  examples/maria/blueprint-v2/maria-blueprint.yaml
  examples/maria/maria-blueprint.yaml
  examples/mongodb-deploymentconfig/README.md
  examples/mongodb-deploymentconfig/blueprint-v2/mongo-dep-config-blueprint.yaml
  examples/mongodb-deploymentconfig/mongo-dep-config-blueprint.yaml
  examples/mongodb-restic/README.md
  examples/mongodb-restic/mongodb-blueprint.yaml
  examples/mongodb/README.md
  examples/mongodb/blueprint-v2/mongo-blueprint.yaml
  examples/mongodb/mongo-blueprint.yaml
  examples/mssql/README.md
  examples/mssql/blueprint-v2/mssql-blueprint.yaml
  examples/mssql/mssql-blueprint.yaml
  examples/mysql-deploymentconfig/README.md
  examples/mysql-deploymentconfig/blueprint-v2/mysql-dep-config-blueprint.yaml
  examples/mysql-deploymentconfig/mysql-dep-config-blueprint.yaml
  examples/mysql/README.md
  examples/mysql/blueprint-v2/mysql-blueprint.yaml
  examples/mysql/mysql-blueprint.yaml
  examples/postgresql-deploymentconfig/README.md
  examples/postgresql-deploymentconfig/blueprint-v2/postgres-dep-config-blueprint.yaml
  examples/postgresql-deploymentconfig/postgres-dep-config-blueprint.yaml
  examples/postgresql-ha/hook-blueprint/README.md
  examples/postgresql-wale/README.md
  examples/postgresql-wale/postgresql-blueprint.yaml
  examples/postgresql/README.md
  examples/postgresql/blueprint-v2/postgres-blueprint.yaml
  examples/postgresql/postgres-blueprint.yaml
  examples/postgresql/v10.16.2/postgres-blueprint.yaml
  examples/time-log/blueprint.yaml
  examples/time-log/time-logger-deployment.yaml
  helm/kanister-operator/Chart.yaml
  helm/kanister-operator/values.yaml
  helm/profile/Chart.yaml
  pkg/app/csi-snapshot.go
  pkg/function/data_test.go
  pkg/function/export_rds_snapshot_location.go
  pkg/function/kube_exec_test.go
  pkg/function/kube_task_test.go
  pkg/function/utils.go
  pkg/kube/pod_test.go
  pkg/testing/e2e_test.go
  scripts/get.sh
Labels: kueue

#1498 Correct typos while adding helm repo in apps
  pkg/app/kafka.go
  pkg/app/mariadb.go
  pkg/app/mysql.go
Labels: kueue

#1499 Upgraded from OpenShift 4.9 to 4.10
  Makefile
  build/integration-test.sh
  pkg/app/utils.go
  pkg/testing/integration_register.go
Labels: kueue

#1458 Update k8s dependencies to 0.24.x
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
Labels: kueue

#1511 Consider some VslmSyncFault errors fatal during FCD SnapshotCreate.
  pkg/blockstorage/vmware/vmware.go
  pkg/blockstorage/vmware/vmware_test.go
Labels: kueue

#1506 Dump Pod Status in logs instead of complete PodSpec
  pkg/kube/pod.go
  pkg/log/log.go
  pkg/log/log_test.go
Labels: kueue

#1509 Update kafka example README
  examples/kafka/adobe-s3-connector/README.md
Labels: kueue

#1518 Add new argument to set annotations in CreatePVCFromSnapshot
  pkg/kube/volume/volume.go
  pkg/kube/volume/volume_test.go
Labels: kueue

#1524 Update log.entry() To Not Use Global Logger
  pkg/log/log.go
  pkg/log/log_test.go
Labels: kueue

#1520 Refactor kubeops test to use custom service names
  pkg/function/kubeops_test.go
Labels: kueue
