Repository kanisterio/kanister, pull requests merged in 2023-04, with the labels that each got.

#1982 Remove Kopia "snapshot gc" command wrapper
  pkg/kopia/command/const.go
  pkg/kopia/command/snapshot.go
Labels: kueue

#1965 Documentation for adding DBSubnetGroup argument to RDS functions
  docs/functions.rst
  docs/spelling_wordlist.txt
Labels: kueue

#1653 Add RepositoryServer controller
  cmd/reposervercontroller/main.go
  go.mod
  go.sum
  pkg/consts/consts.go
  pkg/controllers/repositoryserver/handler.go
  pkg/controllers/repositoryserver/repository.go
  pkg/controllers/repositoryserver/repositoryserver_controller.go
  pkg/controllers/repositoryserver/secrets_manager.go
  pkg/controllers/repositoryserver/server.go
  pkg/controllers/repositoryserver/suite_test.go
  pkg/controllers/repositoryserver/utils.go
  pkg/kopia/command/helpers.go
Labels: kueue

#1985 Updated kubernetes cluster version to 1.26
  Makefile
  build/local_kubernetes.sh
  docker/build/Dockerfile
Labels: kueue

#1987 Prevent dependabot from upgrading github.com/openshift/api
  .github/dependabot.yml
Labels: kueue

#1996 Convert auto-generated repo-controller test to use gocheck
  go.mod
  go.sum
  pkg/controllers/repositoryserver/suite_test.go
Labels: kueue, cleanup

#1991 Add github workflow to build and push kanister image
  .github/workflows/kanister-image-build.yaml
  BUILD.md
Labels: kueue

#2000 build(infra): add package write permissions to workflow
  .github/workflows/kanister-image-build.yaml
Labels: hold off merging

#1992 deps(build): patch version upgrades for k8s dependencies
  go.mod
  go.sum
Labels: kueue, dependencies

#2005 deps(build): upgrade misc k8s.io
  go.mod
  go.sum
Labels: kueue, dependencies

#1988 Upgrade openshift/api to release-4.15 branch
  go.mod
  go.sum
Labels: kueue

#2010 Update ubi-minimal base image to ubi-minimal:9.1.0-1829
  Dockerfile.in
  docker/controller/Dockerfile
  docker/tools/Dockerfile
Labels: kueue

#2014 deps(build): revert "upgrade openshift/api to release-4.15 branch (#1988)"
  go.mod
  go.sum
Labels: kueue

#2016 deps(build): downgrade k8s.io/kube-openapi
  go.mod
  go.sum
Labels: kueue

#2018 deps(build) re-apply "upgrade openshift/api to release-4.15 branch"
  go.mod
  go.sum
Labels: kueue

#2019 Fix code generation command
  go.mod
  go.sum
  pkg/apis/cr/v1alpha1/doc.go
  pkg/apis/cr/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/informers/externalversions/factory.go
Labels: kueue

#1768 Blueprint to Restore Postgres data into RDS database Instance
  examples/postgres-RDS/Dockerfile
  examples/postgres-RDS/README.md
  examples/postgres-RDS/rds-restore-blueprint.yaml
Labels: kueue

#2017 update dependencies
  go.mod
  go.sum
Labels: kueue, dependencies

#2029 Update kopia commit in kanister-tools image v0.13.0-rc2
  .goreleaser.yml
Labels: kueue

#2027 Correct group name in fake clients generation
  pkg/apis/cr/v1alpha1/doc.go
  pkg/client/informers/externalversions/generic.go
Labels: kueue

#1973 Parse kopia errors
  pkg/kopia/command/parse_command_output.go
  pkg/kopia/command/parse_command_output_test.go
Labels: kueue

#1961 Updated etcd example to mention tar availability in pod
  examples/etcd/etcd-in-cluster/k8s/README.md
Labels: kueue

#2040 Revert "deps(go): bump github.com/aws/aws-sdk-go 244 to 250"
  go.mod
  go.sum
Labels: kueue
