Repository kanisterio/kanister, pull requests merged in 2023-09, with the labels that each got.

#2281 add validating webhook for repository server CR
  cmd/reposervercontroller/main.go
  helm/kanister-operator/templates/_helpers.tpl
  helm/kanister-operator/templates/deployment.yaml
  helm/kanister-operator/templates/service.yaml
  helm/kanister-operator/templates/validating-webhook.yaml
  helm/kanister-operator/values.yaml
  pkg/handler/handler.go
  pkg/kancontroller/kancontroller.go
  pkg/validatingwebhook/blueprint_handler.go
  pkg/validatingwebhook/repositoryserver_handler.go
  pkg/validatingwebhook/utils.go
Labels: kueue

#2299 chore(ci): add OSSF Scorecard workflow
  .github/workflows/ossf-scorecard.yml
Labels: security, github_actions

#2294 Add Unit Tests for RepositoryServer Datamover
  build/test.sh
  pkg/datamover/profile.go
  pkg/datamover/repository_server.go
  pkg/datamover/repository_server_test.go
  pkg/datamover/testutils.go
  pkg/datamover/utils.go
Labels: kueue

#2304 deps(go): exclude kopia from automatic dependabot updates
  .github/dependabot.yml
Labels: dependencies, go

#2271 Improve repository server controller tests
  pkg/controllers/repositoryserver/repositoryserver_controller.go
  pkg/controllers/repositoryserver/repositoryserver_controller_test.go
Labels: kueue

#2310 Change the way we figure out container to read the artifacts from
  pkg/controllers/repositoryserver/handler.go
  pkg/controllers/repositoryserver/utils.go
  pkg/kube/pod.go
  pkg/kube/pod_controller.go
  pkg/kube/pod_test.go
Labels: kueue

#2312 Revert "deps(go): bump github.com/prometheus/client_model from 0.3.0 to 0.4.0"
  go.mod
  go.sum
Labels: kueue, dependencies

#2314 Revert "Change the way we figure out container to read the artifacts from"
  pkg/controllers/repositoryserver/handler.go
  pkg/controllers/repositoryserver/utils.go
  pkg/kube/pod.go
  pkg/kube/pod_controller.go
  pkg/kube/pod_test.go
Labels: kueue

#2311 Add new adopter
  ADOPTERS.md
Labels: kueue

#2283 update kopia to a more recent version
  .goreleaser.yml
  go.mod
  go.sum
Labels: kueue

#2274 Remove IBM SoftLayer References
  go.mod
  go.sum
  pkg/blockstorage/const.go
  pkg/blockstorage/getter/getter.go
  pkg/blockstorage/ibm/client.go
  pkg/blockstorage/ibm/client_kube_test.go
  pkg/blockstorage/ibm/client_test.go
  pkg/blockstorage/ibm/const.go
  pkg/blockstorage/ibm/ibmcloud.go
  pkg/blockstorage/ibm/ibmcloud_test.go
  pkg/blockstorage/ibm/testdata/correct/libconfig.toml
  pkg/blockstorage/ibm/testdata/correct/libconfig_old.toml
  pkg/blockstorage/ibm/testdata/incorrect/libconfig.toml
  pkg/blockstorage/ibm/utils/ibmcloud_utils.go
Labels: kueue

#1875 Phase level progress tracking proposal
  design/phase-level-progress-tracking.md
Labels: kueue, frozen

#2330 Fix repositoryserver controller Immutability test
  pkg/controllers/repositoryserver/repositoryserver_controller_test.go
Labels: kueue

#2331 Update ubi-minimal base image to ubi-minimal:9.2-750
  Dockerfile.in
  docker/controller/Dockerfile
  docker/mongodb-atlas/Dockerfile
  docker/tools/Dockerfile
Labels: kueue

#2297 Extract PodControllerProcessor interface and default implementation
  pkg/kube/fake_pod_controller_processor.go
  pkg/kube/pod_command_executor.go
  pkg/kube/pod_command_executor_processor.go
  pkg/kube/pod_command_executor_test.go
  pkg/kube/pod_controller.go
  pkg/kube/pod_controller_processor.go
  pkg/kube/pod_controller_test.go
  pkg/kube/pod_file_writer.go
  pkg/kube/pod_file_writer_processor.go
  pkg/kube/pod_file_writer_test.go
  pkg/kube/pod_runner.go
Labels: kueue

#2295 Pass group version as an argument while creating PVC from volume snapshot
  pkg/kube/volume/volume.go
Labels: kueue

#2298 Improve documentation of PodController and relating interfaces
  pkg/kube/pod_command_executor.go
  pkg/kube/pod_controller.go
  pkg/kube/pod_file_writer.go
Labels: kueue

#2333 Add method to identify group version in the snapshotter interface
  pkg/kube/snapshot/mocks/mock_snapshotter.go
  pkg/kube/snapshot/snapshot.go
  pkg/kube/snapshot/snapshot_alpha.go
  pkg/kube/snapshot/snapshot_beta.go
  pkg/kube/snapshot/snapshot_stable.go
Labels: kueue

#2308 Refactor functions with pod runner
  pkg/function/backup_data_stats.go
  pkg/function/checkRepository.go
  pkg/function/copy_volume_data.go
  pkg/function/delete_data.go
  pkg/function/delete_data_using_kopia_server.go
  pkg/function/describe_backups.go
  pkg/function/prepare_data.go
  pkg/function/restore_data.go
  pkg/function/restore_data_using_kopia_server.go
  pkg/function/utils.go
Labels: kueue

#2316 Revert "Revert "Change the way we figure out container to read the artifacts from""
  pkg/controllers/repositoryserver/handler.go
  pkg/controllers/repositoryserver/utils.go
  pkg/kube/pod.go
  pkg/kube/pod_controller.go
  pkg/kube/pod_test.go
Labels: kueue

#2347 fix build arguments in goreleaser yaml
  .goreleaser.yml
Labels: kueue

#2351 Fix golang vulnerabilities in kanister-tools image
  docker/tools/Dockerfile
Labels: kueue

#2358 Generate and add SBOM to controller container image
  build/package.sh
Labels: kueue

#2234 Refactor Duplicate Functions and Tests from kando package
  pkg/kando/chronicle_pull.go
  pkg/kando/kando_test.go
  pkg/kando/location_delete.go
  pkg/kando/location_pull.go
  pkg/kando/location_push.go
  pkg/kando/location_test.go
Labels: kueue

#2359 Fix formatting issue in documentation for actionsets architecture
  docs/architecture.rst
Labels: kueue
