Repository kanisterio/kanister, pull requests merged in 2024-03, with the labels that each got.

#2708 Enforce FIPS compatible Sprig functions for template rendering
  docs/templates.rst
  pkg/function/wait.go
  pkg/ksprig/fipsonly_sprig.go
  pkg/ksprig/fipsonly_sprig_test.go
  pkg/kube/unstructured_test.go
  pkg/param/param_test.go
  pkg/param/render.go
Labels: kueue

#2718 removed unused jobs code [2395]
  pkg/kube/job.go
  pkg/kube/job_test.go
  pkg/kube/pod.go
Labels: kueue

#2653 Introducing a new approach to building Kopia commands using safecli/command package
  go.mod
  go.sum
  pkg/kopia/cli/doc.go
Labels: enhancement, kueue

#2654 Implement Kopia common args and opts
  pkg/kopia/cli/args/cache_args.go
  pkg/kopia/cli/args/common_args.go
  pkg/kopia/cli/errors.go
  pkg/kopia/cli/internal/args/args.go
  pkg/kopia/cli/internal/args/args_test.go
  pkg/kopia/cli/internal/opts/cache_opts.go
  pkg/kopia/cli/internal/opts/cache_opts_test.go
  pkg/kopia/cli/internal/opts/common_opts.go
  pkg/kopia/cli/internal/opts/common_opts_test.go
  pkg/kopia/cli/internal/opts/opts.go
  pkg/kopia/cli/internal/opts/opts_test.go
Labels: enhancement, kueue

#2717 Improve TransformUnstructured; Log GVK, type value
  pkg/kube/snapshot/snapshot_alpha.go
  pkg/kube/snapshot/snapshot_test.go
Labels: kueue

#2657 Add Kopia GCS storage opts
  pkg/kopia/cli/errors.go
  pkg/kopia/cli/repository/storage/gcs/gcs.go
  pkg/kopia/cli/repository/storage/gcs/gcs_opts.go
  pkg/kopia/cli/repository/storage/gcs/gcs_opts_test.go
  pkg/kopia/cli/repository/storage/gcs/gcs_test.go
Labels: enhancement, kueue

#2659 Add Kopia s3 and s3 compliant storage flags
  pkg/kopia/cli/internal/log/log.go
  pkg/kopia/cli/internal/test/arg_suit.go
  pkg/kopia/cli/repository/storage/s3/s3.go
  pkg/kopia/cli/repository/storage/s3/s3_opts.go
  pkg/kopia/cli/repository/storage/s3/s3_opts_test.go
  pkg/kopia/cli/repository/storage/s3/s3_test.go
Labels: enhancement, kueue

#2661 Add Kopia repository create command
  pkg/kopia/cli/internal/kopia.go
  pkg/kopia/cli/internal/test/command_suite.go
  pkg/kopia/cli/repository/data_test.go
  pkg/kopia/cli/repository/opts.go
  pkg/kopia/cli/repository/opts_test.go
  pkg/kopia/cli/repository/repository_create.go
  pkg/kopia/cli/repository/repository_create_test.go
Labels: enhancement, kueue

#2662 Add Kopia repository connect command
  pkg/kopia/cli/internal/kopia_test.go
  pkg/kopia/cli/repository/opts.go
  pkg/kopia/cli/repository/opts_test.go
  pkg/kopia/cli/repository/repository_connect.go
  pkg/kopia/cli/repository/repository_connect_test.go
Labels: enhancement, kueue

#2711 build(goreleaser): add --pull flag to docker build when building images
  .goreleaser.yml
Labels: kueue

#2663 Add Kopia repository connect server command
  pkg/kopia/cli/errors.go
  pkg/kopia/cli/repository/opts.go
  pkg/kopia/cli/repository/opts_test.go
  pkg/kopia/cli/repository/repository_connect_server.go
  pkg/kopia/cli/repository/repository_connect_server_test.go
Labels: enhancement, kueue

#2664 Add Kopia repository set-parameters command
  pkg/kopia/cli/repository/opts.go
  pkg/kopia/cli/repository/repository_set_parameters.go
  pkg/kopia/cli/repository/repository_set_parameters_test.go
Labels: enhancement, kueue

#2721 Update ubi-minimal base image to ubi-minimal:9.3-1612
  Dockerfile.in
  docker/controller/Dockerfile
  docker/mongodb-atlas/Dockerfile
  docker/tools/Dockerfile
Labels: kueue

#2716 Remove special handling for old bug in dell vxflex csi driver
  pkg/kube/snapshot/snapshot_alpha.go
  pkg/kube/snapshot/snapshot_beta.go
  pkg/kube/snapshot/snapshot_stable.go
Labels: kueue

#2723 build: bump build image tag
  build/run_container.sh
Labels: kueue

#2727 Remove `--pull` from images using kanister-tools as base
  .goreleaser.yml
Labels: kueue

#2728 test: remove extra argument from check calls
  go.mod
  go.sum
  pkg/kopia/cli/internal/test/command_suite.go
Labels: kueue

#2731 Fix a bug in `zoneToRegion` which didn't work if multiple zones where passed separated by `__`
  pkg/blockstorage/blockstorage_test.go
  pkg/blockstorage/gcepd/gcepd.go
  pkg/kube/volume/volume.go
  pkg/kube/volume/volume_test.go
Labels: kueue

#2645 docs(readme): describe commit conventions
  CONTRIBUTING.md
Labels: kueue

#2732 Change deprecated zone and region label with new labels
  pkg/blockstorage/zone/zone_test.go
  pkg/function/create_volume_snapshot_test.go
  pkg/kube/volume/volume.go
Labels: kueue

#2705 Add `provisioned-by` annotations to PVs created by `CreateVolumeFromSnapshot` kanister function
  pkg/consts/consts.go
  pkg/function/create_volume_from_snapshot.go
  pkg/function/create_volume_from_snapshot_test.go
Labels: kueue

#2735 refactor: Satisfy linter in zonesToRegion
  pkg/kube/volume/volume.go
  pkg/kube/volume/volume_test.go
Labels: kueue

#2734 build(ci): cleanup docker images in gha runner before building new images
  .github/workflows/main.yaml
Labels: kueue

#2666 feat!: remove unused blockstorage providers
  go.mod
  go.sum
  pkg/blockstorage/awsefs/awsefs.go
  pkg/blockstorage/awsefs/awsefs_test.go
  pkg/blockstorage/awsefs/conversion.go
  pkg/blockstorage/awsefs/conversion_test.go
  pkg/blockstorage/awsefs/error.go
  pkg/blockstorage/awsefs/filter.go
  pkg/blockstorage/awsefs/wait.go
  pkg/blockstorage/tags/tags.go
  pkg/blockstorage/vmware/conversion.go
  pkg/blockstorage/vmware/conversion_test.go
  pkg/blockstorage/vmware/vmware.go
  pkg/blockstorage/vmware/vmware_manual_test.go
  pkg/blockstorage/vmware/vmware_test.go
Labels: kueue

#2746 Add legacy-api flag to kopia server start command
  pkg/kopia/command/const.go
  pkg/kopia/command/server.go
  pkg/kopia/command/server_test.go
Labels: kueue

#2760 Update filesystem permissions in PostgreSQL app
  pkg/app/postgresql.go
Labels: kueue

#2759 build(docker): update pip dependencies to cover vulnerabilities
  docker/postgres-kanister-tools/Dockerfile
Labels: kueue

#2767 Update kopia commit to 316356a in kanister-tools image
  .goreleaser.yml
  go.mod
  go.sum
Labels: hold off merging

#2769 added resourcesPreset: xlarge for cassandra app
  pkg/app/cassandra.go
Labels: kueue

#2775 fix(tests): Fix flaky TestCloneGlobalLogger
  pkg/log/log_test.go
Labels: kueue

#2777 Set `cluster_name` var in logs vars separately and not in `init`
  cmd/controller/main.go
  cmd/kanctl/main.go
  cmd/reposervercontroller/main.go
  pkg/log/log.go
Labels: kueue

#2790 Update kopia version to 316356a
  .goreleaser.yml
  go.mod
  go.sum
Labels: kueue
