Repository kanisterio/kanister, pull requests merged in 2025-03, with the labels that each got.

#3364 build(github): Fix image scanner output file location
  .github/workflows/images-vulnerability-scanning.yaml
Labels: kueue

#3407 Update build image and linters config to support go1.24
  .golangci.yml
  docker/build/Dockerfile
Labels: kueue

#3405 Add details about images for air-gapped environment
  docs/install.md
Labels: kueue

#3357 [Snyk] Security upgrade setuptools from 40.5.0 to 70.0.0
  docker/build/requirements.txt
Labels: kueue

#3412 build: Change default arch for example images to only build for amd64
  .github/workflows/build_docker.yaml
  .github/workflows/build_example_images.yaml
  .github/workflows/main.yaml
  .github/workflows/release.yaml
Labels: kueue

#3390 fix: Improve options to configure aws rds secret and region
  docs/functions.md
  examples/aws-rds/postgresql/README.md
  examples/aws-rds/postgresql/rds-postgres-dump-blueprint.yaml
  examples/aws-rds/postgresql/rds-postgres-remote-dump-blueprint.yaml
  pkg/app/rds_postgres.go
  pkg/function/rds_utils.go
  pkg/param/param.go
  pkg/phase.go
Labels: kueue

#3406 build: Use new kanister-bot token for charts and projects
  .github/workflows/release.yaml
  .github/workflows/triage-issues.yaml
  .github/workflows/triage-prs.yaml
Labels: kueue

#3422 build: Pin ubi-minimal images using SHA256 in dockerfiles
  Dockerfile.in
  docker/controller/Dockerfile
  docker/repo-server-controller/Dockerfile
  docker/tools/Dockerfile
Labels: kueue, dependencies, docker

#3423 build(github): Pin unpinned github actions
  .github/dependabot.yml
  .github/workflows/pre-release.yml
  .github/workflows/publish_docs.yaml
Labels: dependencies, github_actions

#3426 deps(go): bump go and x/net
  go.mod
  go.sum
Labels: kueue, dependencies, go
